service: whats-gpt
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  account: !Ref 'AWS:AccountId'

hooks:
  'before:deploy:deploy':
    - docker build -t $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION .
    - $(aws ecr get-login --no-include-email)
    - docker tag $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION
    - docker push $DOCKER_REPOSITORY

functions:
  chat:
    image: ${env:DOCKER_IMAGE}
    events:
      - httpApi:
          path: /
          method: post